#version: '3.9'

services:
  api-pet-service:
    container_name: PetMount
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8081:8081'
    depends_on:
      - database
    networks:
      - backend
    restart: on-failure

  database:
    container_name: pet-postgres-db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgresdb" ]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
    postgres-data:

networks:
    backend:
        driver: bridge

