server:
  port: ${SERVER_PORT:8080}
  address: ${SERVER_ADDRESS:localhost}

spring:
  application:
    name: PetMount
  profiles:
    active: dev

logging:
  level:
    root: INFO
    web: OFF
    org.springframework: INFO
    org.apache: OFF
    kafka: OFF